[build]
  publish = "build/"
  # This will be your default build command
  command = "yarn build"
  [build.processing.css]
    bundle = true
    minify = false
  [build.processing.js]
    bundle = true
    minify = false
  [build.processing.html]
    pretty_urls = true
  [build.processing.images]
    compress = true

[[redirect]]
  from="/*"
  to="/index.html"
  status=200